name: release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.7.6

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: yarn test

      - name: Compile
        run: pnpm build

      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
